export interface ThemeConfig {
  id: string;
  name: string;
  cssVars: Record<string, string>;
  bodyClass: string;
}

export const themes: ThemeConfig[] = [
  {
    id: "rust",
    name: "РЖАВЧИНА",
    cssVars: {
      "--bg-primary": "#0a0a0c",
      "--bg-secondary": "#111114",
      "--bg-card": "#16161a",
      "--text-primary": "#c8c4bc",
      "--text-secondary": "#6b6560",
      "--text-muted": "#3d3a38",
      "--accent": "#8b6914",
      "--accent-dim": "#5a4510",
      "--accent-glow": "rgba(139, 105, 20, 0.15)",
      "--border": "#252428",
      "--border-dim": "#1a191e",
      "--rust-overlay": "url(\"data:image/svg+xml,%3Csvg width='100' height='100' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100' height='100' filter='url(%23noise)' opacity='0.03'/%3E%3C/svg%3E\")",
      "--scanline-opacity": "0.08",
      "--font-heading": "'Courier New', monospace",
      "--font-body": "'Courier New', monospace",
      "--corner-decoration": "block",
      "--dust-particles": "block",
      "--hyena-decoration": "none",
      "--chamomile-decoration": "none",
      "--stripe-border": "none",
      "--tv-frame": "none",
      "--chalk-border": "none",
    },
    bodyClass: "theme-rust",
  },
  {
    id: "ash",
    name: "ПЕПЕЛ",
    cssVars: {
      "--bg-primary": "#0c0c0c",
      "--bg-secondary": "#141414",
      "--bg-card": "#1a1a1a",
      "--text-primary": "#a0a0a0",
      "--text-secondary": "#666666",
      "--text-muted": "#333333",
      "--accent": "#555555",
      "--accent-dim": "#3a3a3a",
      "--accent-glow": "rgba(85, 85, 85, 0.15)",
      "--border": "#222222",
      "--border-dim": "#181818",
      "--rust-overlay": "none",
      "--scanline-opacity": "0.12",
      "--font-heading": "'Courier New', monospace",
      "--font-body": "'Courier New', monospace",
      "--corner-decoration": "none",
      "--dust-particles": "none",
      "--hyena-decoration": "none",
      "--chamomile-decoration": "none",
      "--stripe-border": "block",
      "--tv-frame": "none",
      "--chalk-border": "none",
    },
    bodyClass: "theme-ash",
  },
  {
    id: "kenli69",
    name: "KENLI69",
    cssVars: {
      "--bg-primary": "#1a1520",
      "--bg-secondary": "#231d2e",
      "--bg-card": "#2d2540",
      "--text-primary": "#e8d5f0",
      "--text-secondary": "#9b8aa8",
      "--text-muted": "#5a4e68",
      "--accent": "#c8a4e0",
      "--accent-dim": "#8b6aaa",
      "--accent-glow": "rgba(200, 164, 224, 0.2)",
      "--border": "#3d3252",
      "--border-dim": "#2d2440",
      "--rust-overlay": "none",
      "--scanline-opacity": "0.04",
      "--font-heading": "'Courier New', monospace",
      "--font-body": "'Courier New', monospace",
      "--corner-decoration": "none",
      "--dust-particles": "none",
      "--hyena-decoration": "block",
      "--chamomile-decoration": "block",
      "--stripe-border": "none",
      "--tv-frame": "block",
      "--chalk-border": "block",
    },
    bodyClass: "theme-kenli69",
  },
];

export function getThemeById(id: string): ThemeConfig {
  return themes.find((t) => t.id === id) || themes[0];
}
